services:
  postgres:
    image: postgres
    container_name: postgres-container
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: change_me
      POSTGRES_DB: mine_search_db
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U user -d mine_search_db
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network
    volumes:
      - postgres-data:/var/lib/postgresql
    restart: unless-stopped
  worker:
    image: ghcr.io/kauri-off/mine_search/worker:latest
    volumes:
      - ./config.toml:/app/config.toml:ro
    networks:
      - app-network
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
  backend:
    image: ghcr.io/kauri-off/mine_search/backend:latest
    volumes:
      - ./config.toml:/app/config.toml:ro
    networks:
      - app-network
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
  frontend:
    image: ghcr.io/kauri-off/mine_search/frontend:latest
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 8080:80
    depends_on:
      - backend
      - frontend
    networks:
      - app-network
    restart: unless-stopped
  watchtower:
    image: containrrr/watchtower
    environment:
      - WATCHTOWER_POLL_INTERVAL=3600
      - WATCHTOWER_CLEANUP=true
      - DOCKER_API_VERSION=1.44
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
networks:
  app-network:
volumes:
  postgres-data:
