// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ServerDataResponse = { server_id: number, online: number, max: number, players: Array<string>, timestamp: string, };
