// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type ServerDataResponse = { server_id: number, online: number, max: number, players: JsonValue, timestamp: string, };
