// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ServerSnapshotsResponse = { server_id: number, players_online: number, players_max: number, recorded_at: string, };
