// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateServerRequest = { server_ip: string, is_checked: boolean | null, is_spoofable: boolean | null, is_crashed: boolean | null, };
