CREATE TABLE IF NOT EXISTS servers (
    id SERIAL PRIMARY KEY,
    ip VARCHAR NOT NULL UNIQUE,
    port INTEGER NOT NULL,
    version_name VARCHAR NOT NULL,
    protocol INTEGER NOT NULL,
    description JSONB NOT NULL,
    license BOOLEAN NOT NULL,
    white_list BOOLEAN,
    checked BOOLEAN,
    auth_me BOOLEAN,
    crashed BOOLEAN,
    was_online BOOLEAN DEFAULT TRUE NOT NULL,
    created TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS data (
    id BIGSERIAL PRIMARY KEY,
    server_id INTEGER NOT NULL REFERENCES servers(id) ON DELETE CASCADE,
    online INTEGER NOT NULL,
    max INTEGER NOT NULL,
    players JSONB NOT NULL,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);
