ALTER TABLE data ADD COLUMN players JSONB NOT NULL DEFAULT '[]';
ALTER TABLE data ALTER COLUMN players DROP DEFAULT;

ALTER TABLE servers ADD COLUMN unique_players INTEGER NOT NULL DEFAULT 0;
ALTER TABLE servers ALTER COLUMN unique_players DROP DEFAULT;

DROP TABLE players;
DROP TYPE player_status;